targets:
  flugger:flugger:
    builders:
      flugger:
        enabled: True
        
builders:
  flugger:
    import: "package:flugger/flugger.dart"
    builder_factories: ["swaggerBuilder"]
    build_extensions:
      "$lib$": [".swagger.dart", ".models.dart", ".converter.dart"]
    build_to: source
    auto_apply: dependents