# THIS FILE WILL BE IN THE PARENT PROJECTS ROOT AND WILL BE USED TO SPECIFY OPTIONS FOR THIS TOOL, OPTIONS WILL BE LIKE THIS:
generic_imports: #default: empty
  - 'package:onedigital_customer/_all.dart'
swagger: #default: null
  # url: 'https://petstore.swagger.io/v2/swagger.json' # Example 1
  url: 'https://capi.portal.onedigital.de/swagger/v1/swagger.json' # Example 2
destination_path_prefix: './lib/domain/models/'
extensions_destination_path_prefix: './lib/extensions/general/'
structure: 
  type: structured #default: structured
  convention: namespace #default: namespace
request:
  name_sufix: 'RequestModel' #default: 'RequestModel'
  name_part_to_remove: 'Request' #default: 'Request'
  parent_folder_name: 'request_models' #default: 'request_models'
  copyWith: true #default: true
  fromJson: false #default: false
  toJson: true #default: true
response:
  name_sufix: 'ResponseModel' #default: 'ResponseModel'
  name_part_to_remove: 'Response' #default: 'Response'
  parent_folder_name: 'response_models' #default: 'response_models'
  copyWith: false #default: false
  fromJson: true #default: true
  toJson: false #default: false
search:
  name_sufix: 'SearchModel' #default: 'SearchModel'
  name_part_to_remove: 'Search' #default: 'Search'
  parent_folder_name: 'search_models' #default: 'search_models'
  copyWith: true #default: true
  fromJson: false #default: false
  toJson: true #default: true
model:
  name_sufix: 'Model' #default: 'Model'
  name_part_to_remove: 'Model' #default: 'Model'
  parent_folder_name: 'models' #default: 'models'
  copyWith: true #default: true
  fromJson: true #default: true
  toJson: true #default: true