name: flugger
description: "Map Swagger models to Flutter/Dart models in your project"
version: 0.1.1
repository: https://github.com/salihagic/flugger

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^1.5.0
  dio: ^5.4.3+1
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  args: ^2.5.0

flutter:

executables:
  flugger: flugger