name: flugger
description: "Map Swagger models to Flutter/Dart models in your project"
version: 0.1.11
repository: https://github.com/salihagic/flugger

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^2.0.0
  dio: ^5.8.0+1
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  args: ^2.7.0

flutter:

executables:
  flugger: flugger