name: flugger
description: "Map Swagger models to Flutter/Dart models in your project"
version: 1.0.0
repository: https://github.com/salihagic/flugger

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^4.0.2
  dio: ^5.9.0
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.10.0
  args: ^2.7.0
  flutter_lints: ^6.0.0

flutter:

executables:
  flugger: flugger