// ignore_for_file: non_constant_identifier_names

import 'package:flugger/flugger.dart';
import 'package:yaml/yaml.dart';

/// Flugger options that get populated from values from flugger.yaml file from parent project
class FluggerOptions {
  /// Defines structure of the output files/folders
  final StructureFluggerOptions structure;

  /// Specifies relative path to destination of generated files/folders
  final String destination_path_prefix;

  /// Specifies relative path to destination of generated extensions file that are used by models generated by this tool
  final String extensions_destination_path_prefix;

  /// Specifies a list of generic imports that will be generated at the top of every generated file by this tool
  final List<String> generic_imports;

  /// Options for model of type Request (usually have name sufix RequestModel and generate copyWith and toJson methods)
  final ModelFluggerOptions request;

  /// Options for model of type Response (usually have name sufix ResponseModel and generate fromJson method)
  final ModelFluggerOptions response;

  /// Options for model of type Search (usually have name sufix SearchModel and generate copyWith and toJson methods)
  final ModelFluggerOptions search;

  /// Options for model of type basic Model (usually have name sufix Model and generate copyWith, fromJson and toJson methods)
  final ModelFluggerOptions model;

  /// Options for model of type basic Model (usually have name sufix Model and generate copyWith, fromJson and toJson methods)
  final EnumFluggerOptions enums;

  /// Swagger options to specify url from where to fetch models schema
  final SwaggerFluggerOptions? swagger;

  /// Log information as the content gets generated
  final bool logging;

  FluggerOptions({
    required this.structure,
    required this.destination_path_prefix,
    required this.extensions_destination_path_prefix,
    required this.generic_imports,
    required this.request,
    required this.response,
    required this.search,
    required this.model,
    required this.enums,
    required this.swagger,
    required this.logging,
  });

  /// Parsing method used by this tool to parse the values from flugger.yaml file to strongly typed FluggerOptions
  factory FluggerOptions.fromYamlMap(YamlMap map) {
    return FluggerOptions(
      structure: map['structure'] != null
          ? StructureFluggerOptions.fromYamlMap(map['structure'])
          : StructureFluggerOptions.initial(),
      destination_path_prefix: map['destination_path_prefix'] ?? '',
      extensions_destination_path_prefix:
          map['extensions_destination_path_prefix'] ?? '',
      generic_imports:
          map['generic_imports']?.map<String>((x) => x as String).toList() ??
              [],
      request: map['request'] != null
          ? ModelFluggerOptions.fromYamlMap(map['request'])
          : ModelFluggerOptions.initialRequest(),
      response: map['response'] != null
          ? ModelFluggerOptions.fromYamlMap(map['response'])
          : ModelFluggerOptions.initialResponse(),
      search: map['search'] != null
          ? ModelFluggerOptions.fromYamlMap(map['search'])
          : ModelFluggerOptions.initialSearch(),
      model: map['model'] != null
          ? ModelFluggerOptions.fromYamlMap(map['model'])
          : ModelFluggerOptions.initialModel(),
      enums: map['enum'] != null
          ? EnumFluggerOptions.fromYamlMap(map['enums'])
          : EnumFluggerOptions.initial(),
      swagger: map['swagger'] != null
          ? SwaggerFluggerOptions.fromYamlMap(map['swagger'])
          : null,
      logging: map['logging'] ?? false,
    );
  }
}
